### ISSUE TITLE
UART3 RX and TX HANDLER is swap in header file

### ISSUE THREAD

**Issue by MarrekNozka** [gicking/STM8-SPL_SDCC_patch#11]
Use interupts from UART3 is'n possible witch sdcc. Because:

https://github.com/gicking/STM8-SPL_SDCC_patch/blob/a65f8df8560ae715a6bb736738fe9b819b2ee0fe/STM8S_StdPeriph_Lib_V2.3.1_sdcc.patch#L3263-L3264

UART3 RX and TX HANDLER and numbers of interupts is swap in header file. This is right version:

```c
 INTERRUPT_HANDLER(UART3_TX_IRQHandler, 20);              /* UART3 TX */
 INTERRUPT_HANDLER(UART3_RX_IRQHandler, 21);              /* UART3 RX */

```
this version corresponds with functions bodies in `stm8s_it.c`:

https://github.com/gicking/STM8-SPL_SDCC_patch/blob/a65f8df8560ae715a6bb736738fe9b819b2ee0fe/STM8S_StdPeriph_Lib_V2.3.1_sdcc.patch#L16105-L16122

**Comment by gicking** [comment]
thanks for the feedback! I just uploaded a new patch which fixes this bug. Please let me know if it works. Thanks in advance!

**Comment by gicking** [comment]
no feedback -> close issue. If the issue persists, please re-open or open new issue

**Comment by MarrekNozka** [comment]
I'm sorry for my delay. It's alright. It works for me.

**Comment by gicking** [comment]
:-)
