### ISSUE TITLE
File to patch

### ISSUE THREAD

**Issue by PocketPi** [gicking/STM8-SPL_SDCC_patch#13]
Hey

I am trying to apply the patch but i cannot get it working, 

I get the following output when trying to run the script: 

`
The next patch would create the file ./STM8L15x-16x-05x-AL31-L_StdPeriph_Lib/Doxyfile,
which already exists!  Assume -R? [n] y
patching file ./STM8L15x-16x-05x-AL31-L_StdPeriph_Lib/Doxyfile
can't find file to patch at input line 2358
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff -rcN ./STM8L15x-16x-05x-AL31-L_StdPeriph_Lib/Libraries/STM8L15x_StdPeriph_Driver/inc/stm8l15x.h ./STM8L15x-16x-05x-AL31-L_StdPeriph_Lib_V1.6.2_sdcc/Libraries/STM8L15x_StdPeriph_Driver/inc/stm8l15x.h
|*** ./STM8L15x-16x-05x-AL31-L_StdPeriph_Lib/Libraries/STM8L15x_StdPeriph_Driver/inc/stm8l15x.h	2014-10-22 14:31:38.000000000 +0200
|--- ./STM8L15x-16x-05x-AL31-L_StdPeriph_Lib_V1.6.2_sdcc/Libraries/STM8L15x_StdPeriph_Driver/inc/stm8l15x.h	2019-02-03 09:08:54.078042546 +0100
--------------------------
File to patch: ^C
peter:/media/peter/data/code/sb-batteryboks3_2/STM8L15x-16x-05x-AL31-L_StdPeriph_Lib$ ll
total 11M
drwxrwxrwx 1 peter peter 4,0K May  9 09:43  .
drwxrwxrwx 1 peter peter 4,0K May  9 09:41  ..
-rwxrwxrwx 1 peter peter  880 May  9 09:42  apply_patch.sh
-rwxrwxrwx 1 peter peter 100K May  9 09:43  Doxyfile
drwxrwxrwx 1 peter peter    0 Oct 22  2014  _htmresc
drwxrwxrwx 1 peter peter    0 Oct 22  2014  Libraries
-rwxrwxrwx 1 peter peter  18K Oct 22  2014 'MCD-ST Liberty SW License Agreement V2.pdf'
drwxrwxrwx 1 peter peter    0 Oct 22  2014  Project
-rwxrwxrwx 1 peter peter  77K Oct 22  2014  Release_Notes.html
drwxrwxrwx 1 peter peter  152 May  9 09:49  STM8L15x-16x-05x-AL31-L_StdPeriph_Lib
-rwxrwxrwx 1 peter peter 9,4M Oct 22  2014  stm8l15x-16x-05x-al31-l_stdperiph_lib_um.chm
-rwxrwxrwx 1 peter peter 612K May  9 09:41  STM8L15x-16x-05x-AL31-L_StdPeriph_Lib_V1.6.2_sdcc.patch
drwxrwxrwx 1 peter peter    0 Oct 22  2014  Utilities
peter:/media/peter/data/code/sb-batteryboks3_2/STM8L15x-16x-05x-AL31-L_StdPeriph_Lib$ 
`

Please help me apply the patch :)

**Comment by gicking** [comment]
Hi Peter,

sorry for the late reply! I tried to reproduce the error and indeed found an issue. Specifically some files in the SPL are read-only, which triggered some error messages - though different ones from the above...

So here's what I did: 

1. log into https://st.com
2. search for "STSW-STM8016" (see Readme.md)
3. download SPL v1.6.2 for STM8L15x-16x-05x-AL31-L 
4. create empty test folder
5. extract ZIP file in test folder -> "STM8L15x-16x-05x-AL31-L_StdPeriph_Lib"
6. from commandline type "chmod -R u+w ./STM8L15x-16x-05x-AL31-L_StdPeriph_Lib"
7. copy "apply_patch.sh" and "STM8L15x-16x-05x-AL31-L_StdPeriph_Lib_V1.6.2_sdcc.patch" to test folder
8. in file "apply_patch.sh" uncomment line 15 and comment lines 14, 16, 17 -> select correct patchfile 
9. from commandline type "apply_patch.sh" 

With step 6 (=make all files writable) I don't get any error message, see attached [output.txt](https://github.com/gicking/STM8-SPL_SDCC_patch/files/11469190/output.txt). Therefore I now added  step 6 into "apply_patch.sh" on the repo (-> no need to do manually).

As your error message looks quite different, I am not sure it fixes your problem. Nevertheless can you please try the above sequence and let me know? Thanks a lot in advance!

**Comment by gicking** [comment]
Actually your error messages seem to indicate that you tried to patch an already modified folder. So please make certain you start from a fresh download (step 3 above)

**Comment by gicking** [comment]
Haven't heard anything in 3 weeks, therefore I assume this topic is closed...!? If not, please just re-open it

**Comment by PocketPi** [comment]
Thanks, i didnt see the comment, but it worked
