### ISSUE TITLE
Trap IRQHandler declaration in STM8L15x-16x-05x-AL31-L_StdPeriph_Lib should postfix with __trap

### ISSUE THREAD

**Issue by aguegu** [gicking/STM8-SPL_SDCC_patch#4]
With the latest patch, all `stm8l15x_it.h` in `STM8L15x_StdPeriph_Examples`, line 81

```
void TRAP_IRQHandler(void);                                          /* TRAP */
```
should be 

```
void TRAP_IRQHandler(void) __trap;                              /* TRAP */
```

like in other examples, (STM8L10X, STM8S).

Otherwise, it will cause error like
```
stm8l15x_it.c:71: error 98: conflict with previous declaration of 'TRAP_IRQHandler' for attribute 'interrupt' at ../common/stm8l15x_it.h:81
```

**Comment by gicking** [comment]
hi aguegu,

thanks for pointing this out! I just uploaded the fixed patch. Hope it works now...!?

Regards, Georg

**Comment by aguegu** [comment]
@gicking Cool. I just have bought all mini stm8 boards available online. : )
