### ISSUE TITLE
function 'IS_FLASH_ADDRESS_OK' implicit declaration in STM8L15x-16x-05x-AL31-L_StdPeriph_Lib stm8l15x_flash.c

### ISSUE THREAD

**Issue by aguegu** [gicking/STM8-SPL_SDCC_patch#8]
STM8L15x-16x-05x-AL31-L_StdPeriph_Lib/Libraries/STM8L15x_StdPeriph_Driver/src/stm8l15x_flash.c:472: warning 112: function 'IS_FLASH_ADDRESS_OK' implicit declaration.

It should be `IS_FLASH_ADDRESS` defined in `stm8l15x_flash.h`

I know it should be an `official` issue. But since the official guys do not use github that much. Maybe we can create one for them? 

What do you think?

**Comment by gicking** [comment]
hi aguegu,
thanks a lot for you testing feedback! I fixed that bug and also found a few bugs in header filenames (wrong case -> ok in Windoze, nok in POSIX). Can you please check and give me feedback? Thanks a lot in advance!
Georg

**Comment by aguegu** [comment]
I have not seen any header filenames issues for now. 

I still would like to see an independent repository for SPLs taking the official ones as upstream and keep tracking them.

What you commit/patch on patches is hard to review or track. 

I believe you have got enough knowledge on the licenses issue. and with the effects of the community, that repo would be merged back to the official SPL and make SDCC win.

**Comment by gicking** [comment]
thanks again, your support is highly appreciated!

I fully understand and agree that patchfiles are an rather awkward way! Ideally STM would just come around to also support SDCC. And the 2nd best solution would be a source code repo, e.g. on Github.

But unfortunately the license situation is quite unclear to me. Specifically on the SPL download pages they refer to the "Mix Ultimate Liberty+OSS+3rd-party V1 - SOFTWARE LICENSE AGREEMENT" v4.10, but included in the download is the "Software License Agreement (Liberty V2)". The first allows source re-distribution within limits (see [here](https://github.com/gicking/STM8-SPL_SDCC_patch/issues/1)), the 2nd one not. As I am not a lawyer I'd rather not take the risk and wait until the fog has cleared. Sorry!

Proposal: as you seem to really work with the SPL and I don't, how about you propose this to STM directly in their [STM8 forum](https://community.st.com)? Alternatively contact Philipp Krause, as he seems to be in close contact with STM about all kinds of SDCC topics. 

Sorry for this reply and have a nice day :-)

**Comment by aguegu** [comment]
I have tried the forum. It is hard to point to the problem and also lack of discussion. 

The License problem is interesting. Next month, there would be ST official conference in my city. I would throw it to the face of ST guys if I got a chance. :) Thank you for making it clear to me.

**Comment by gicking** [comment]
hello again,
actually I faced the same problem in contacting the right people at STM a while ago. However, Philipp Krause of the SDCC team seems to be more successful.
 
But, as said, I would happily give up this patching if ST just supported SDCC as well. Look at how Atmel does and how it benefits them!

Good luck and let me know what you achieved!

**Comment by gicking** [comment]
discussion via PM
